version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_eco_renov
    restart: always
    environment:
      POSTGRES_USER: steve
      POSTGRES_PASSWORD: root
      POSTGRES_DB: eco_renov_solutions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
